# Generated by Django 5.0.4 on 2024-04-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_request_request_category_alter_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestor',
            field=models.CharField(default=''),
        ),
    ]
