# Generated by Django 5.0.4 on 2024-04-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_request_requestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requestor',
        ),
    ]
