# Generated by Django 5.0.4 on 2024-04-05 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField()),
                ('company_name', models.CharField()),
                ('forgot_password_token', models.CharField(null=True)),
                ('forgot_password_expiry', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(default=datetime.datetime(2024, 4, 5, 18, 32, 43, 565641, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
